default: &default
  adapter: postgresql
  encoding: unicode
  username: SEU_USERNAME
  password: SUA_SENHA
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: NOME_DO_BANCO_DE_DADOS_development

test:
  <<: *default
  database: NOME_DO_BANCO_DE_DADOS_test

production:
  <<: *default
  database: NOME_DO_BANCO_DE_DADOS_production
